### ISSUE TITLE
Events are not being send encoded anymore

### ISSUE THREAD

**Issue by jnicolaes** [AdobeDocs/adobe-io-events#57]
Issue in /src/pages/guides/index.md

Recently we've made changes to decode the events received from IO events. This was a part of recent security changes by adobe. However last month we are seeing the events weren't being encoded at all anymore. Could you please provided clarity and if this is expected?

**Comment by shikhartanwar** [comment]
@jnicolaes What events do you subscribe for? The security changes done should only affect the headers that I/O events sends, not the encoding of the actual event payload.

**Comment by jnicolaes** [comment]
@shikhartanwar , we've subscribed to analytics triggers

**Comment by shikhartanwar** [comment]
> @shikhartanwar , we've subscribed to analytics triggers

We don't make changes to the event payload coming from Analytics Triggers. The [security changes](https://developer.adobe.com/events/docs/guides/#security-considerations) you are talking about do not affect the payload at all.

**Comment by jnicolaes** [comment]
@shikhartanwar thanks for confirming that, let me discuss it internally and see if that piece of info might solve our issue
